name: AppBlocks.Core
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore NuGet Packages
      run: nuget restore ${{github.workflow}}.sln
    - name: Build with MSBuild
      run: msbuild ${{github.workflow}}.sln -p:Configuration=Release
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/${{github.workflow}}/${{github.workflow}}.csproj
        PACKAGE_NAME: ${{github.workflow}}
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        VERSION_FILE_PATH: src/${{github.workflow}}/bin/Release/${{github.workflow}}.0.0.1.nupkg
        # Regex pattern to extract version info in a capturing group
        #VERSION_REGEX: # optional, default is ^\s*<Version>(.*)<\/Version>\s*$
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        VERSION_STATIC: 0.0.1 # optional
        # Flag to toggle git tagging, enabled by default
        #TAG_COMMIT: # optional, default is true
        # Format of the git tag, [*] gets replaced with actual version
        #TAG_FORMAT: # optional, default is v*
        NUGET_KEY: ${{secrets.NUGET_KEY}} # optional
